### ISSUE TITLE
Is this open to build upon?

### ISSUE THREAD

**Issue by debuggermalhotra** [ematvey/pybacktest#24]
Hi! First of all great library. I was looking for something like this as I am looking for a backtester for http://docs.kloudtrader.com. It's always better to extend something instead of reinventing the wheel but I don't see any License. So i wanted to seek permission to extend this library! Lemme know if this could be possible.
Thanks!

**Comment by ematvey** [comment]
Hi! Thanks for your interest. I've added a LICENSE file.

**Comment by malhotrachetan** [comment]
Thanks. Appreciated and Acknowledged. 👍🏼
